# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 08:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid_upload_path.storage
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('mobile', models.CharField(max_length=10, null=True)),
                ('work_location', models.TextField(blank=True, null=True, verbose_name='Present Company')),
                ('work_experience', models.FloatField(blank=True, null=True, verbose_name='Work Experience')),
                ('github', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('googleplus', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('personal_blog', models.URLField(blank=True, null=True)),
                ('organization_website', models.URLField(blank=True, null=True)),
                ('profile_pic', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=uuid_upload_path.storage.upload_to)),
            ],
        ),
    ]
